
name: Mirror to Second Repo

on:
  push:
    branches:
      - main

jobs:
  mirror_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Save Mirror Config
        run: |
          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@://github.com/avinashnandakumar//world-cup-fantasy-roast-squad.git
          git fetch mirror main || true
          git checkout mirror/main -- config.js || true
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Keep mirror config.js" || true

      - name: Push to Mirror
        run: |
          git push --force mirror refs/remotes/origin/*:refs/heads/* tags/*:tags/*